version: "3.7"
services:
  service-web:
    restart: always
    image: zhasst/kc-web:latest
    ports:
      - "8081:80"
    container_name: container-web
    volumes:
      - "./config/config.php:/var/www/html/config.php"
      - "./config/config.js:/var/www/html/lib/config.js"
      - "./config/apache2.conf:/etc/apache2/apache2.conf"
      - "./log:/var/log/apache2"
      - "./docs:/var/www/html/docs"
    networks:
      - kc-net
networks:
  kc-net:
    external:
      name: kc-net
